
- name: MacOS | Install kubebuilder
  homebrew:
    name: kubebuilder
    state: latest
  tags:
    - brew
  when: ansible_facts['os_family'] == "Darwin"

- name: Debian | Install kubebuilder
  include_role:
    name: andrewrothstein.kubebuilder
  when: ansible_facts['os_family'] != "Darwin"
