- name: vaulttec.zsh
- name: fubarhouse.golang
- name: andrewrothstein.kubectl
- name: andrewrothstein.kubebuilder
- name: diodonfrost.terraform
- name: andrewrothstein.k9s
- name: andrewrothstein.kubernetes-helm
- name: geerlingguy.docker
- name: christiangda.awscli

