---

- name: "Debian | Configure protoc endpoint for Debian"
  set_fact:
    protoc_endpoint: "protoc-{{ protoc_ver }}-linux-x86_64.zip"

- name: "Debian | Install dependencies"
  apt:
    pkg: [ 'libzmq3-dev', 'tar', 'software-properties-common', 'locales' ]
    state: present
  register: apt_result
  until: apt_result is success
  retries: 1
  delay: 2

- name: "Debian | Define GOARCH"
  set_fact:
    GOARCH: "amd64"
  when: GOARCH is not defined

- name: "Debian | Define GOOS"
  set_fact:
    GOOS: "linux"
  when: GOOS is not defined
