- name: MacOS | Install docker
  homebrew_cask:
    name: docker
    state: present
  tags:
    - brew
  when: ansible_facts['os_family'] == "Darwin"

- name: Linux | Install docker
  include_role:
    name: geerlingguy.docker
  when: ansible_facts['os_family'] != "Darwin"