
- name: Set GOPATH directory permissions
  file:
    name: "{{ ansible_env.HOME }}/go"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    recurse: yes
  changed_when: false

- name: Export GOPATH in zshrc
  lineinfile:
    dest: "{{ zshrc_path }}"
    line: "export PATH={{ GOPATH }}:{{ GOPATH}}/bin:$PATH"
    state: present

- name: Export GO111MODULE in zshrc
  lineinfile:
    dest: "{{ zshrc_path }}"
    line: "export GO111MODULE=on"
    state: present

- name: Export GOPRIVATE in zshrc
  lineinfile:
    dest: "{{ zshrc_path }}"
    line: "GOPRIVATE=wwwin-github.cisco.com/slimshady"
    state: present
